config/routes.rb
Skillcult::Application.routes.draw do
  devise_for :users

  get "welcome/index"

  root 'welcome#index'

  resources :users, :projects, :houses, :skills

  

end

app/models/house.rb
class House < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/skill.rb
class Skill < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  def index
    @houses = House.all
  end

  def new
  end

  def create
    @house = House.new(house_params)

    @house.save
    redirect_to @house
  end

  def show
    @house = House.find(params[:id])
  end

  private
    def house_params
      params.require(:post).permit(:title, :text)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
  end

  def create
    @project = Project.new(project_params)

    @project.save
    redirect_to @project
  end

  def show
    @project = Project.find(params[:id])
  end

  private
    def project_params
      params.require(:post).permit(:title, :text)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    @skills = Skill.all
  end

  def new
  end

  def create
    @skill = Skill.new(skill_params)

    @skill.save
    redirect_to @skill
  end

  def show
    @skill = Skill.find(params[:id])
  end

  private
    def skill_params
      params.require(:post).permit(:title, :text)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/houses/index.html.erb
<h1>Listing houses</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @houses.each do |house| %>
    <tr>
      <td><%= house.title %></td>
      <td><%= house.text %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Add New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New House</h1>
<%= form_for :post, url: houses_path do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>
<%= link_to 'View Houses', houses_path %>

app/views/houses/show.html.erb
<p>
  <strong>Title:</strong>
    <%= @house.title %>
</p>
<p>
  <strong>Text:</strong>
    <%= @house.text %>
</p>
<%= link_to 'View Houses', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body id="page">
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->

<!-- Top Bar -->
  <header class="top-bar">
      <h1 class="logo">
        <a class="button menu-link" href="#">SC</a><% if user_signed_in? %>&nbsp;<%= current_user.email %><% end %>
      </h1>

      <div class="tools">
      <% if user_signed_in? %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "Sign in", new_user_session_path %>
      <% end %>
      </div>
  </header>


<!-- Messages -->
  <section id="messages" class="main">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </section>

<!-- Main Content Area -->
  <section id="container" class="main">
    <div class="row attention">
      <!-- Add your site or application content here -->
    </div>

    <h1>Skillcult</h1>

    <%= yield %>

    
  <script type="text/x-handlebars">
    {{outlet}}
  </script>

  <script type="text/x-handlebars" id="projects">
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <table class='table'>
            <thead>
              <tr><th>Recent Projects</th></tr>
            </thead>
            {{#each model}}
            <tr><td>
              {{#linkTo 'project' this}}{{title}} <small class='muted'>by {{author}}</small>{{/linkTo}}
            </td></tr>
            {{/each}}
          </table>
        </div>
        <div class="span9">
          {{outlet}}
        </div>
      </div>
    </div>
  </script>

  <script type="text/x-handlebars" id="projects/index">
    <p class="text-warning">Please select a project</p>
  </script>

  <script type="text/x-handlebars" id="project">
    {{#if isEditing}}
      {{partial 'project/edit'}}
      <button {{action 'doneEditing'}}>Done</button>
    {{else}}
      <button {{action 'edit'}}>Edit</button>
    {{/if}}

    <h1>{{title}}</h1>
    <h2>by {{author}} <small class='muted'>({{date publishedAt}})</small></h2>

    <hr>

    <div class='intro'>
      {{markdown intro}}
    </div>

    <div class='below-the-fold'>
      {{markdown extended}}
    </div>
  </script>

  <script type="text/x-handlebars" id="project/_edit">
    <p>{{view Ember.TextField valueBinding='title'}}</p>
    <p>{{view Ember.TextArea valueBinding='intro'}}</p>
    <p>{{view Ember.TextArea valueBinding='extended'}}</p>
  </script>

  <script type="text/x-handlebars" id="about">
    <div class='about'>
      <p>Yehuda Katz is a member of the <a href="http://emberjs.com">Ember.js</a>, <a href="http://rubyonrails.org">Ruby on Rails</a>
      and <a href="http://www.jquery.com">jQuery</a> Core Teams; he spends his daytime hours at the startup he founded,
      <a href="http://www.tilde.io">Tilde Inc.</a>.</p>
      <p>Yehuda is co-author of best-selling <a href="http://affiliate.manning.com/idevaffiliate.php?id=485_176">jQuery in Action</a> and
      <a href="http://affiliate.manning.com/idevaffiliate.php?id=485_145">Rails 3 in Action</a>.</p>
      <p>He spends most of his time hacking on open source—his main projects, along with others, like <a href="https://github.com/wycats/thor">Thor</a>,
      <a href="http://www.handlebarsjs.com">Handlebars</a> and <a href="https://github.com/carlhuda/janus">Janus</a>—or traveling the world doing evangelism work.</p>
      <p>He can be found on Twitter as <a href="http://www.twitter.com/wycats">@wycats</a>.</p>
    </div>

    <div class='about'>
      <p>My name is Tom Dale. I helped create <a href="http://www.emberjs.com/">Ember.js</a>, a JavaScript framework that brings sanity to the web.</p>

      <p>In October of 2011, I co-founded <a href="http://www.tilde.io">Tilde</a> with Yehuda Katz, Leah Silber and Carl Lerche.</p>

      <p>In my spare time I run a cash-for-beer exchange program at many local San Francisco dive bars.</p>
    </div>
  </script>


  </section>

  </body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% @projects.each do |project| %>
<div class="row">
  <article>
    <header>
      <h1><%= project.title %></h1>
    </header>
    <aside><%= project.intro %></aside>
    <p><%= project.extended %></p>
    <footer>
      <p>Conjured by: <%= project.author %></p>
    </footer>  
  </article>
</div>
<% end %>
<div class="row">
  <%= link_to 'New Project', new_project_path %>
</div>


<!-- projects ember main -->
<script type="text/x-handlebars" data-template-name="index">
  <section id="main">
    {{#each controller}}
     <article>
      <h2>{{title}}</h2>
      <p>{{text}}</p>
    </article>
    {{/each}}
    <nav class="row">
      <%= link_to 'Add New Project', new_project_path %>
    </nav>
  </section>
</script>

<!-- new -->
<script type="text/x-handlebars" data-template-name="new">
  <section id="new">
  <%= form_for :post, url: projects_path do |f| %>
    <fieldset>
      <%= f.label :title %>
      <%= f.text_field :title, { class: 'text' } %>
    </fieldset>
    <fieldset>
      <%= f.label :text %>
      <%= f.text_area :text, { class: 'text' } %>
    </fieldset>
    <fieldset>
      <%= f.submit %>
    </fieldset>
  <% end %>
    <nav class="row">
      <%= link_to 'View Projects', projects_path %>
    </nav>
  </section>
</script>

<!-- show -->
<script type="text/x-handlebars" data-template-name="show">
  <section id="show">
    <article>
      <h2>Skillcult</h2>
      <p>Ut culpa high life qui whatever. Aute nostrud nihil next level tofu, id readymade wes anderson ut hoodie. Deserunt wes anderson tattooed minim, blog quis laboris eu. Proident trust fund twee, nesciunt quinoa biodiesel wes anderson freegan you probably haven't heard of them PBR consectetur viral. Delectus velit occaecat brooklyn, vice leggings in irure adipisicing jean shorts cupidatat blog cliche voluptate. Cupidatat tumblr wolf velit blog, nisi food truck sunt pitchfork irure. American apparel aliquip single-origin coffee, biodiesel organic mixtape master cleanse portland vero deserunt wolf quinoa farm-to-table next level.</p>
    </article>
    <%= link_to 'View Projects', projects_path %>
  </section>
</script>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= form_for :post, url: projects_path do |f| %>
	<fieldset>
	  <%= f.label :title %>
		<%= f.text_field :title %>
	</fieldset>
	<fieldset>
	  <%= f.label :author %>
		<%= f.text_field :author %>
	</fieldset>
	<fieldset>
		<div>
			<%= f.label :intro %>
			<%= f.text_area :intro, cols: 30, rows: 3 %>
		</div>
	</fieldset>
	<fieldset>
		<div>
			<%= f.label :extended %>
			<%= f.text_area :extended, cols: 30, rows: 6 %>
		</div>
	</fieldset>
	<fieldset class="form-actions">
	  <%= f.submit %>
		<%= link_to 'Cancel', projects_path %>
	</fieldset>
<% end %>

app/views/projects/show.html.erb
<div class="row">
  <article>
    <header>
      <h1><%= @project.title %></h1>
    </header>
    <aside><%= @project.intro %></aside>
    <p><%= @project.extended %></p>
    <footer>
      <p>Conjured by: <%= @project.author %></p>
    </footer>  
  </article>
</div>
<div class="row">
  <%= link_to 'Projects', projects_path %>
</div>

app/views/skills/index.html.erb
<h1>Listing skills</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>

  <% @skills.each do |skill| %>
    <tr>
      <td><%= skill.title %></td>
      <td><%= skill.text %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Add New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New Skill</h1>
<%= form_for :post, url: skills_path do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :text %><br>
  <%= f.text_area :text %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>
<%= link_to 'View Skills', skills_path %>

app/views/skills/show.html.erb
<p>
  <strong>Title:</strong>
    <%= @skill.title %>
</p>
<p>
  <strong>Text:</strong>
    <%= @skill.text %>
</p>
<%= link_to 'View Skills', skills_path %>

app/views/users/index.html.erb
<h3>Users</h3>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.email, user %> signed up <%= user.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.id %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/welcome/index.html.erb
<h1>Hello Skillcult!</h1>

<!-- Forms -->
<div class="row">
  <h2>Form: Top Labels</h2>
  <!-- Form: Samples -->
  <form class="" action="/">
    <fieldset>
      <label for="name">First Name</label>
      <input type="text" id="name" class="text" />
      <p class="form-help">This is help text under the form field.</p>
    </fieldset>

    <fieldset>
      <label for="email">Last Name</label>
      <input type="email" id="email" class="text" />
    </fieldset>

    <fieldset class="form-actions">
      <input type="submit" value="Next" />
      <input type="button" value="Disabled" class="disabled" />
    </fieldset>
  </form>
  
  <h2>Form: Inset Labels</h2>
  <form class="inset" action="/">
    <fieldset>
      <label for="name">First Name</label>
      <input type="text" id="name" class="text" />
      <p class="form-help">This is help text under the form field.</p>
    </fieldset>

    <fieldset>
      <label for="email">Last Name</label>
      <input type="email" id="email" class="text" />
    </fieldset>

    <fieldset class="form-actions">
      <input type="submit" value="Next" />
      <input type="button" value="Disabled" class="disabled" />
    </fieldset>
  </form>
  
  <h2>Buttons: Various</h2>
  <form action="/">
    <fieldset>
      <p><input type="button" value="Input type attention" class="attention"></p>
      <p><input type="reset" value="Input type alert" class="alert"></p>
      <p><input type="submit" value="Input type warning" class="warning"></p>
      <p><input type="submit" value="Input type submit disabled" class="disabled" disabled></p>
      <p><button type="button" class="success">Button type success</button></p>
      <p><button type="reset" class="value">Button type value</button></p>
      <p><button type="submit">Button type submit</button></p>
      <p><button type="button" class="disabled" disabled>Button type button disabled</button></p>
      <p><button>Button</button></p>
      <p><button type="button" class="secondary">Secondary button</button></p>
      <p><button type="button" class="secondary disabled" disabled>Secondary button disabled</button></p>
    </fieldset>
  </form>
</div>

<!-- Headers -->
<div class="row">
  <!-- Headers -->
  <h1>Heading 1 with <small>small text</small> and a <a href="#">link</a></h1>
  <h2>Heading 2 with <small>small text</small> and a <a href="#">link</a></h2>
  <h3>Heading 3 with <small>small text</small> and a <a href="#">link</a></h3>
  <h4>Heading 4 with <small>small text</small> and a <a href="#">link</a></h4>
  <h5>Heading 5 with <small>small text</small> and a <a href="#">link</a></h5>
  <h6>Heading 6 with <small>small text</small> and a <a href="#">link</a></h6>
  
  <!-- Headers in Article -->
  <article>
    <h1>Heading 1 (in article) with <small>small text</small> and a <a href="#">link</a></h1>
    <h2>Heading 2 (in article) with <small>small text</small> and a <a href="#">link</a></h2>
    <h3>Heading 3 (in article) with <small>small text</small> and a <a href="#">link</a></h3>
    <h4>Heading 4 (in article) with <small>small text</small> and a <a href="#">link</a></h4>
    <h5>Heading 5 (in article) with <small>small text</small> and a <a href="#">link</a></h5>
    <h6>Heading 6 (in article) with <small>small text</small> and a <a href="#">link</a></h6>
  </article>
</div>

<!-- Lists -->
<div class="row">
<h2>Lists</h2>
<!-- List: Unordered -->
  <ul>
    <li>list item 1</li>
    <li>list item 1
      <ul>
        <li>list item 2</li>
        <li>list item 2
          <ul>
            <li>list item 3</li>
            <li>list item 3</li>
          </ul>
        </li>
        <li>list item 2</li>
        <li>list item 2</li>
      </ul>
    </li>
    <li>list item 1</li>
    <li>list item 1</li>
  </ul>
</div>

<!-- Ordered Lists -->
<div class="row">
<!-- List: Ordered -->
  <ol>
    <li>list item 1</li>
    <li>list item 1
      <ol>
        <li>list item 2</li>
        <li>list item 2
          <ol>
            <li>list item 3</li>
            <li>list item 3</li>
          </ol>
        </li>
        <li>list item 2</li>
        <li>list item 2</li>
      </ol>
    </li>
    <li>list item 1</li>
    <li>list item 1</li>
  </ol>
</div>

<!-- Definitions -->
<div class="row">
<!-- List: Definition -->
  <dl>
    <dt>Description name</dt>
      <dd>Description value</dd>
    <dt>Description name</dt>
      <dd>Description value</dd>
      <dd>Description value</dd>
  </dl>
</div>

<!-- Tables -->
<div class="row">
  <h2>Tables</h2>
  <table>
    <caption>Table Caption</caption>
    <thead>
      <tr>
        <th>thead th</th>
        <th>thead th</th>
        <th>thead th</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>tbody td</td>
        <td>tbody td</td>
        <td>tbody td</td>
      </tr>
      <tr>
        <td>tbody td</td>
        <td>tbody td</td>
        <td>tbody td</td>
      </tr>
    </tbody>
    <tfoot>
      <tr>
        <th>tfoot th</th>
        <th>tfoot th</th>
        <th>tfoot th</th>
      </tr>
    </tfoot>
  </table>

  <h3>Table with side headings</h3>
  <table>
    <caption>Table Caption</caption>
    <thead>
      <tr>
        <th>thead th</th>
        <th>thead th</th>
        <th>thead th</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>tbody th</th>
        <td>tbody td</td>
        <td>tbody td</td>
      </tr>
      <tr>
        <th>tbody th</th>
        <td>tbody td</td>
        <td>tbody td</td>
      </tr>
    </tbody>
    <tfoot>
      <tr>
        <th>tfoot th</th>
        <td>tfoot td</td>
        <td>tfoot td</td>
      </tr>
    </tfoot>
  </table>
</div>

<div class="row">
  <h2>Type</h2>
  <!-- Type -->
  <p>The <a href="#">a element</a> example</p>
  <p>The <abbr>abbr element</abbr> and an <abbr title="Abbreviation">abbr</abbr> element with title examples</p>
  <p>The <b>b element</b> example</p>
  <p>The <cite>cite element</cite> example</p>
  <p>The <code>code element</code> example</p>
  <p>The <em>em element</em> example</p>
  <p>The <del>del element</del> example</p>
  <p>The <dfn>dfn element</dfn> and <dfn title="Title text">dfn element with title</dfn> examples</p>
  <p>The <i>i element</i> example</p>
  <p>The <ins>ins element</ins> example</p>
  <p>The <kbd>kbd element</kbd> example</p>
  <p>The <mark>mark element</mark> example</p>
  <p>The <q>q element</q> example</p>
  <p>The <q>q element <q>inside</q> a q element</q> example</p>
  <p>The <s>s element</s> example</p>
  <p>The <samp>samp element</samp> example</p>
  <p>The <small>small element</small> example</p>
  <p>The <span>span element</span> example</p>
  <p>The <strong>strong element</strong> example</p>
  <p>The <sub>sub element</sub> example</p>
  <p>The <sup>sup element</sup> example</p>
  <p>The <u>u element</u> example</p>
  <p>The <var>var element</var> example</p>
  
  <!-- Blockquote -->
  <blockquote>
    <p>Some sort of famous witty quote marked up with a &lt;blockquote> and a child &lt;p> element.</p>
  </blockquote>
  
  <blockquote>Even better philosophical quote marked up with just a &lt;blockquote> element.</blockquote>
</div>
  
<div class="row">
  <h2>Media</h2>
  <!-- Media -->
  <figure>
    <img src="http://placehold.it/240x240" alt="alt text">
    <figcaption>Figcaption content</figcaption>
  </figure>

  <figure>
    <img src="http://placehold.it/240x240" alt="alt text">
    <figcaption>
    <h4>Figure Title</h4>
    Figcaption content
    </figcaption>
  </figure>
</div>

<div class="row">
  <h2>More Forms</h2>
  <!-- Forms -->
  <form>
    <fieldset>
      <div><label>Text input</label> <input type="text"></div>
      <div><label>Text input with placeholder</label> <input type="text" placeholder="I'm placeholder text"></div>
      <div><label>Readonly input</label> <input type="text" value="Read only text input" readonly></div>
      <div><label>Disabled input</label> <input type="text" value="Disabled text input" disabled></div>
      <div><label>Required input <span class="required">*</span></label> <input type="text" required></div>
      <div><label>Email input</label> <input type="email"></div>
      <div><label>Search input</label> <input type="search"></div>
      <div><label>Speech recognition input</label> <input type="text" id="speech" name="speech" x-webkit-speech=""></div>
      <div><label>Tel input</label> <input type="tel"></div>
      <div><label>Phone (International)</label> <input name="field_country_code" maxlength="3" /> - <input name="field_city_code" maxlength="4" /> - <input name="field_phone_int" maxlength="8" /></div>
      <div><label>URL input</label> <input type="url" placeholder="http://"></div>
      <div><label>Password input</label> <input type="password" value="password"></div>
      <div><label>Select field</label> <select><option>Option 01</option><option>Option 02</option></select></div>
      <div><label>Multiple select field</label><select multiple size="5"><option>Option 1</option><option>Option 2</option><option>Option 3</option><option>Option 4</option><option>Option 5</option><option>Option 6</option><option>Option 7</option><option>Option 8</option><option>Option 9</option><option>Option 10</option></select></div>
      <div><label>Radio input</label> <input type="radio" name="rad"></div>
      <div><label>Checkbox input</label> <input type="checkbox"></div>
      <div><label><input type="radio" name="rad"> Radio input</label></div>
      <div><label><input type="checkbox"> Checkbox input</label></div>
      <div><label>File input</label> <input type="file"></div>
      <div><label>Textarea</label> <textarea cols="30" rows="5" >Textarea text</textarea></div>
      <div><label>Color input</label> <input type="color" value="#000000"></div>
      <div><label>Number input</label> <input type="number" value="5" min="0" max="10"></div>
      <div><label>Range input</label> <input type="range" id="range" value="0" min="0" max="100"> <output for="range">0</output>
      <script>
      if (document.querySelector) {
      document.querySelector('#range').onchange = function(e) {
      e.target.nextElementSibling.innerText = e.target.value;
      }
      }
      </script>
      </div>
      <div><label>Date input</label> <input type="date"></div>
      <div><label>Month input</label> <input type="month"></div>
      <div><label>Week input</label> <input type="week"></div>
      <div><label>Time input</label> <input type="time"></div>
      <div><label>Datetime input</label> <input type="datetime"></div>
      <div><label>Datetime-local input</label> <input type="datetime-local"></div>
    </fieldset>
  </form>
</div>

<div class="row">
  <h2>Article Objects</h2>
  <!-- Article -->
  <article>
    <header>
      <h2>The Title Goes Here</h2>
    </header>
    
    <aside>
      This is aside text lorem ipsum dolor sit amet consectetur adipisicing.
    </aside>
    
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis <a href="#">nostrud exercitation</a> ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod <a href="#">tempor incididunt</a> ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit.</p>
    <footer>
      Posted August 22, 2011
    </footer>
  </article>

  <!-- Slats List -->
  <ul class="slats">
    <li class="group">
      <a href="#">
        <img src="images/thumb.png" alt="thumbnail" />
        <h3>This is the title</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. <span class="meta">August 10, 2011</span></p>
      </a>
    </li>
  </ul>

  <form action="/">
    <fieldset>
      <label for="gender">Gender</label>
      <select id="gender">
      <option>Male</option>
      <option>Female</option>
      <option>Cylon</option>
      </select>
    </fieldset>

    <fieldset class="radio">
      <label for="notifications">Notifications</label>
      <ul>
      <li><label><input type="radio" name="notifications" /> Send me email</label></li>
      <li><label><input type="radio" name="notifications" /> Don't send me email</label></li>
      <li><label><input type="radio" name="notifications" /> Send me flowers</label></li>
      </ul>
    </fieldset>

    <fieldset>
      <label for="url">URL</label>
      <input type="url" id="url" class="form-text" placeholder="http://yourdomain.com" />
    </fieldset>

    <fieldset>
      <label for="bio">Bio</label>
      <textarea id="bio"></textarea>
    </fieldset>

    <fieldset class="check">
      <label><input type="checkbox" /> I accept the terms of service and lorem ipsum.</label>
    </fieldset>

    <fieldset class="form-actions">
      <input type="submit" value="Submit" />
    </fieldset>

  </form>
</div>